modLoader = "javafml" #mandatory
loaderVersion = "[47,)" # You can set this to the specific range of Forge versions you want to support.
license = "MIT" # Your mod's license. Choose the appropriate license for your project.

[[mods]]
modId = "better_hp" # Your mod's ID, which is usually the same as your package name.
version = "1.0.0" # Your mod's version.
displayName = "Better HP" # The display name of your mod.
authors = "BanditBytes" # Replace with your name or username.
description = '''
This mod displays the player's health above the health bar in the HUD.
''' # Description of your mod.

[[dependencies."better_hp"]]
modId = "forge" #mandatory
mandatory = true #mandatory
versionRange = "[47.0.0,)" # Set this to the Forge version range you support.
ordering = "NONE"
side = "CLIENT" # Change this to CLIENT

[[dependencies."better_hp"]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,1.21.0)" # This version range declares compatibility with 1.20.1 up to but not including 1.21.0.
ordering = "NONE"
side = "CLIENT" # Change this to CLIENT
